### PR TITLE
fixtures as class attributes

### PR DESCRIPTION
**Pull request by skraynev**
@nicoddemus @hackebrot  Hi all, sorry for the delay. Could you please review the article, mentioned in:
https://github.com/pytest-dev/pytest/issues/2618

### CODE REVIEW

**Comment by skraynev** [comment]
Looks like someone have to merge it :)

**Comment by nicoddemus** [comment]
@skraynev thanks for the ping, appreciate it! 

Hope you don't mind but I made some small changes to grammar and wording in a few places, also changed the second example to show the technique being applied to standard `unittest` subclasses because I believe this will be the main audience of the article. 

Again, thanks for your work on this contribution. @hackebrot would you like to take another look before we merge it?

**Comment by skraynev** [comment]
I have reviewed it rapidly, so I don't mind to merge it with your improvements :+1:

**Comment by nicoddemus** [comment]
Thanks again @skraynev!

**Comment by little-dude** [comment]
This is a really useful trick. Would you consider making such `auto_inject_fixtures` decorator part of pytest itself @nicoddemus ?

**Comment by nicoddemus** [comment]
Hi @little-dude,

Probably not in my opinion, but I would really love for it to get more prominence somehow...

**Pull request merged**
